### ISSUE TITLE
l2 regularization explanation

### ISSUE THREAD

**Issue by joaogui1** [deep-learning-indaba/indaba-pracs-2022#27]
Hi! I believe there's a typo in the explanation of $l_2$ regularization in the Bayesian Deep Learning Practical
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/13261989/185799915-1a45c1f0-2619-4508-82d0-0f8d6bd63c40.png">
Where it reads small it should be large.
@JavierAntoran @JamesAllingham

**Comment by JavierAntoran** [comment]
Fixed in latest PR. Many thanks @joaogui1!
